# Generated by Django 4.2.28 on 2026-02-16 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_faviourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faviourite',
            new_name='Favourite',
        ),
    ]
